### PR TITLE
change release workflow to do everything manually

### PR DESCRIPTION
**Pull request by lindgrenj6**

### CODE REVIEW

**Comment by lindgrenj6** [comment]
cc @syncrou @gmcculloug updating this to do it manually like we do with approval/rbac.

**Review by syncrou — APPROVED** [review]
LGTM 👍

**Comment by slemrmartin** [comment]
@lindgrenj6 what does it mean? How the release works with this PR?

**Comment by lindgrenj6** [comment]
So - basically in #31 I tried to use a pre-made Github Action that someone in the community made which uses `rake release` etc, but that one didn't work. This PR changed the way the Github Workflow worked so that it just does the gem build/gem release/git tag manually. 

It does seem to have worked though with the most recent push! :tada:

**Pull request merged**
