### PR TITLE
Use released version of topological_inventory-api-client

### PR DESCRIPTION
**Pull request by agrare**

### CODE REVIEW

**Comment by slemrmartin** [comment]
How to use `override_gem` in development after that? I think it will stop working

**Comment by agrare** [comment]
@slemrmartin override_gem still works with gems in a gemspec

```
adam@desktop:~/src/topology/topological_inventory-providers-common$ cat bundler.d/override_gem.rb 
override_gem "topological_inventory-api-client", :path => "~/src/topology/topological_inventory-api-client-ruby"
adam@desktop:~/src/topology/topological_inventory-providers-common$ bundle show topological_inventory-api-client
** override_gem("topological_inventory-api-client", :path=>"/home/grare/adam/src/topology/topological_inventory-api-client-ruby") at /home/grare/adam/src/topology/topological_inventory-providers-common/bundler.d/override_gem.rb:1
/home/grare/adam/src/topology/topological_inventory-api-client-ruby
```

**Comment by slemrmartin** [comment]
It didn't work (relatively log time ago) in persister -> core -> inventory_refresh hierarchy. So it was probably bug. Thanks for info

**Review by slemrmartin — APPROVED** [review]
:+1:

**Pull request merged**
