### PR TITLE
Added refresh-type to save and sweep inventory

### PR DESCRIPTION
**Pull request by slemrmartin**
**Issue**: https://github.com/RedHatInsights/topological_inventory-persister/issues/66

Adding refresh_type: string to Inventory to help recognizing the type of payload in persister. 

Defaults to "full-refresh"

---

**Depends on**
- [x] https://github.com/RedHatInsights/topological_inventory-ingress_api-client-ruby/pull/68
- [x] https://github.com/RedHatInsights/topological_inventory-ingress_api-client-ruby/pull/69

### CODE REVIEW

**Review by syncrou — APPROVED** [review]
LGTM 👍 - when green.

**Comment by syncrou** [comment]
@slemrmartin looks like we have a problem with the specs.

**Comment by slemrmartin** [comment]
retesting worked

**Comment by slemrmartin** [comment]
Note: This can't be deployed without persister and ingress-api changes, so I recommend not to merge it before #46 if we want to deliver the fix in 1.0.8 to prod earlier

**Review by syncrou — APPROVED** [review]
LGTM 👍 Specs are green now.

**Pull request merged**
