### PR TITLE
Common Metrics exporter

### PR DESCRIPTION
**Pull request by slemrmartin**
**Issue** https://github.com/RedHatInsights/topological_inventory-api/issues/320

- Common class for custom metrics
- Common Operations Processor with time measurement
- Metrics collecting in availability check

---

[RHCLOUD-9945](https://issues.redhat.com/browse/RHCLOUD-9945)
[RHCLOUD-9949](https://issues.redhat.com/browse/RHCLOUD-9949)

### CODE REVIEW

**Review by lindgrenj6 — APPROVED** [review]
Looks good, one thing we're going to need to check is whether all of the operations pods have port 9394 exposed in a service, that is necessary in the newer OCPv4 environments.

**Comment by slemrmartin** [comment]
@lindgrenj6 is it this? https://github.com/RedHatInsights/e2e-deploy/blob/0c55cc2c90a29611004a1352df5be64cb103ba52/templates/topological-inventory/topological-inventory-ansible-tower-operations.yml#L16 
It's present in all operation templates

**Review by syncrou — APPROVED** [review]
LGTM 👍

**Comment by lindgrenj6** [comment]
> @lindgrenj6 is it this? https://github.com/RedHatInsights/e2e-deploy/blob/0c55cc2c90a29611004a1352df5be64cb103ba52/templates/topological-inventory/topological-inventory-ansible-tower-operations.yml#L16
> It's present in all operation templates

Yep! Looks good.

**Pull request merged**
