### PR TITLE
Release 1.0.6

### PR DESCRIPTION
**Pull request by lindgrenj6**
depends on:
- [x] https://github.com/RedHatInsights/topological_inventory-providers-common/pull/38

cc @gmcculloug @slemrmartin @syncrou

### CODE REVIEW

**Comment by slemrmartin** [comment]
@lindgrenj6 Please add #35 to the Changelog and add release date to 1.0.5

**Comment by lindgrenj6** [comment]
@slemrmartin: @gmcculloug and I were talking yesterday as well, maybe we could just manually restart the build(s) in OCP rather than updating the gemfile, since it should just pull the right version down during the build. Is that something you would be open to?

**Comment by slemrmartin** [comment]
@lindgrenj6 it can work unless there is some cache during build. 

I'll rather see the minimal version needed in Gemfiles but I can live with both options :)

**Comment by lindgrenj6** [comment]
@slemrmartin cool, we actually have caching turned off for builds so there shouldn't be any cache, so it should work! I'd definitely rather have minimal versions as well, that way we'd only have to bump when the behavior changes. 

example: https://github.com/RedHatInsights/e2e-deploy/blob/4a15f9cd24e9368bd662af2deb03a57b7196520a/buildfactory/topological-inventory/topological-inventory-amazon.yml#L30

@gmcculloug I'll get a script together so we can restart all the builds that use the gem.

**Comment by slemrmartin** [comment]
..thinking about it more, when rebuilding manually, we have to keep in mind that we have to rebuild all images manually in qa and prod. Updating gemfile will ensure the change is propagated automatically and we can be sure we don't forget to rebuild 1 collector

**Comment by lindgrenj6** [comment]
@slemrmartin yes exactly, I'd rather have a script that does it or maybe even a jenkins job, that way none of them get forgotten.

**Comment by lindgrenj6** [comment]
@gmcculloug @slemrmartin heres the script, threw it in my k8s-dev-utils repo which has a bunch of other scripts for working with ocp. 

Martin let me know if I missed any images, I think these are the only ones that really need to be rebuilt, I don't think api/ingress/persister need to be rebuilt?
https://github.com/lindgrenj6/k8s-dev-utils/blob/master/rebuild_all.rb

**Comment by slemrmartin** [comment]
@lindgrenj6 is the script intended to rebuild all images with providers-common gem? Then `orchestrator` doesn't contain it and `sync` needs to be added. Other repos are not using it

**Comment by lindgrenj6** [comment]
@slemrmartin yes this is to rebuild all of the images that rely on the providers-common gem. I have it updated, lmk if it looks good enough.

**Review by slemrmartin — APPROVED** [review]

**Pull request merged**
