### PR TITLE
Add logging method to base collector

### PR DESCRIPTION
**Pull request by lindgrenj6**
https://projects.engineering.redhat.com/browse/TPINVTRY-881

Add logging method to base class so that we can just call this method from any collector. 

This is for https://github.com/RedHatInsights/topological_inventory-ansible_tower/pull/82

cc @gtanzillo @syncrou @slemrmartin

### CODE REVIEW

**Review by slemrmartin — CHANGES_REQUESTED** [review]
:+1: LGTM, just increase gem version (lib/..VERSION)

**Review by syncrou — APPROVED** [review]
LGTM 👍 (waiting on @slemrmartin feedback to be applied. )

**Comment by slemrmartin** [comment]
Note: Will be released together with #19 (as I knew about this PR), but it needs to update collectors' Gemfiles to compatible manageiq-loggers first (before release, because they have `~> 1.0.0` version

**Comment by lindgrenj6** [comment]
@slemrmartin @syncrou incremented gem version to 1.0.1

**Review by slemrmartin — APPROVED** [review]

**Pull request merged**
